[package]
name = "miden-node-faucet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug-assertions = true

[dependencies]
actix-web = "4"
actix-files = "0.6.5"
actix-cors = "0.7.0"
anyhow = "1"
derive_more = "0.99.17"
miden-client = { git = "https://github.com/0xPolygonMiden/miden-client", branch = "main" }
miden_objects = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
