[book]
authors      = ["Miden contributors"]
description  = "Manual for the Miden node software which is responsible for aggregating transactions into blocks for the Miden blockchain."
language     = "en"
multilingual = false
title        = "The Miden Node Operator and Developer Guide"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/miden-node"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
